Replace big element with CSS
Use the `big` CSS class instead of the obsolete `<big>` tag.

Fixes the following HTML validator warning:

> Error: The big element is obsolete. Use CSS instead.