npc.php: fix error buying hardware
Use `IFloor` instead of `floor` to compute the amount of each hardware
to buy so that we have an int instead of a float. Fixes:

> TypeError: doUNO(): Argument #2 ($amount) must be of type int, float given