Fix stale social login URLs
If you leave the login page open for longer than the PHP session
timeout and then click a social login link, then an exception is
thrown because the PHP session data has expired.

For Facebook, the error will look something like:

FacebookSDKException: Cross-site request forgery validation failed.
Required param "state" missing from persistent data.

To fix this, we no longer display the social login URL on the login
page. Instead, we link to a wrapper `login_social_processing.php`,
construct the social login URL there, and then immediately forward
to it to ensure that the session that's created while generating
the URL is still active.