logException: fix too long messages in admin box
The `message_boxes.message_text` column is type TEXT, which has a limit
on the string length. When logging exceptions, make sure we restrict the
length of the message to this limit to avoid a database error.