Fix error with NPC ship upgrades
The NPC ship upgrades were failing as of 8babe4bc due to not passing
in the required `LocationID` var data.

> Exception: Could not find "LocationID" in var!

Because the `LocationID` is only used for the HTML display, it doesn't
matter what its value is for NPCs (we arbitrarily choose "-1").