Fix error in message sending
For alliance and global messages, there is no `receiver` in the var,
so we should not try to transfer it to a container. Similarly, we only
have `alliance_id` in the var if we are sending an alliance message.

Fixes errors along the lines of:

> Exception: Could not find "receiver" in var!